--CREACION DE TABLAS
CREATE TABLE Persona (CI INT, NOMBRE TEXT, APELLIDO TEXT, EDAD INT)
CREATE TABLE Vehiculo(MATRICULA TEXT, MARCA TEXT, MODELO TEXT, COLOR TEXT)

--INSERCIÓN DE DATOS
INSERT INTO Persona(CI, NOMBRE, APELLIDO, EDAD) VALUES(1,'NOM 1', 'APE 1', 35)
INSERT INTO Persona(CI, NOMBRE, APELLIDO) VALUES(2,'NOM 2', 'APE 2')
INSERT INTO Persona(CI, NOMBRE, APELLIDO, EDAD) VALUES(3,'NOM 3', 'APE 3', 40)

--ACTUALIZACIÓN DE DATO
UPDATE Persona SET EDAD = 38 WHERE CI = 2 

--INSERCIÓN DE DATOS
INSERT INTO Vehiculo(MATRICULA, MARCA, MODELO)VALUES('ABC 1234', 'VW', 'GOL')
INSERT INTO Vehiculo(MATRICULA, MARCA, MODELO, COLOR)VALUES('BCD 2345', 'FIAT', 'UNO', 'AZUL')
INSERT INTO Vehiculo(MATRICULA, MARCA, MODELO, COLOR)VALUES('CDE 3456', 'FORD', 'FOCUS', 'ROJO')
INSERT INTO Vehiculo(MATRICULA, MARCA, MODELO, COLOR)VALUES('DEF 4567', 'VW', 'GOL', 'MARRON')

--ACTUALIZACIÓN DE DATOS
UPDATE Vehiculo SET COLOR = 'AMARILLO' WHERE MODELO = 'GOL' 

--CONSULTAS
SELECT CI, NOMBRE, APELLIDO, EDAD FROM Persona WHERE CI = 1 
SELECT CI, NOMBRE FROM Persona 
SELECT * FROM Vehiculo WHERE MODELO = 'GOL' 
SELECT * FROM Vehiculo WHERE MODELO LIKE '%G%'
 





